### PR TITLE
MERGE FIRST:css changes

### PR DESCRIPTION
**Pull request by haitzlm**

### CODE REVIEW

**Review by hortongn — COMMENTED** [review]
Can you provide a description in the PR of what changes I should look for when reviewing.  Also describe why you made changes to config/environments/development.rb

**Comment by haitzlm** [comment]
updated: # for debugging javascript on dev. Should help destroy to work as well in dev. 

  config.assets.compile = true
  config.assets.digest = false

**Comment by haitzlm** [comment]
- Moved table display of employees to left, to make screen bigger
- created new div to keep the headers of page aligned with left margin (so everything has the wide left margin)
- changed a couple h1 to h2 for correctness
- fixed the signin area below the uc footer to align better. 
- fixed admin area alignment with li's corrected

for the development.rb file, this value:
config.action_controller.perform_caching = true

In trying to fix the javascript error on destroy, we ran a compile before deploy. That itself created another issue where the CSS was broken.

Putting into development.rb these values fixed the css- and were set mostly for debugging the javascript in dev. I dont think i need them in production. 

config.assets.compile = true
  config.assets.digest = false

**Comment by haitzlm** [comment]
hmnn perplexing. can you check the javascript link in the header of html page and let me know the address?

Lisa Haitz

Developer
UC Libraries
________________________________

**Comment by hortongn** [comment]
The link is
http://localhost:3000/packs/js/application-b74e82561692dfd08320.js

The file resolves for me, but in the middle of the JS file source is this error:
```
throw new Error("Module build failed (from ./node_modules/babel-loader/lib/index.js):\nError: Cannot find package '@babel/plugin-proposal-private-methods' imported from /Users/hortongn/Development/uclibs/staff-directory/babel-virtual-resolve-base.js
```

**Comment by haitzlm** [comment]
so - i think you need both branches to get it to work locally. perhaps i should have moved the confit/environments/development.rb from css branch to javascript branch .

Lisa Haitz

Developer
UC Libraries
________________________________

**Comment by haitzlm** [comment]
hmnn that's new . ok - will check

Lisa Haitz

Developer
UC Libraries
________________________________

**Comment by haitzlm** [comment]
so babel is required, obviously. the error you are getting is saying Babel is unable to find the package @babel/plugin-proposal-private-methods. This  is in the package.json and  yarn.lock (line 462) as well as a babel.config.js. 
So, it appears your dev environment has to be updated? ChatGPT suggests the following, which you probably already know, but thought I would document here:

```
Here's a step-by-step guide to resolve the issue related to Babel and the missing @babel/plugin-proposal-private-methods package:

1. Pull the Latest Code from GitHub

Ensure your colleague has the latest version of the code:

    Pull from GitHub: He should pull the latest changes from the repository to make sure his local codebase is up to date.

    bash

    git pull origin main  # Replace 'main' with whatever your default branch is

2. Install JavaScript Dependencies

After updating the code, the next step is to ensure that all JavaScript dependencies are correctly installed:

    Install Packages with Yarn: If your project uses Yarn (which is common in Rails projects using Webpacker), your colleague should run:

    bash

    yarn install

    This command installs all dependencies defined in package.json and ensures that yarn.lock is updated and in sync.

3. Check for Configuration Discrepancies

    Ensure Correct Babel Configuration: Verify that the babel.config.js is set up correctly in his environment, as per the repository. It should include @babel/plugin-proposal-private-methods if your application requires it.
    Sync Configuration Files: Make sure all configuration files, such as webpacker.yml and any specific environment settings in config/webpack, are correctly set up and consistent with what's working in your environment.

4. Clear Caches

Sometimes, stale caches can cause issues:

    Clear Yarn Cache: Run yarn cache clean.
    Clear Webpacker Cache: Sometimes, it helps to clear the cache that Webpacker might have:

    bash

    ./bin/webpacker clean  # Or the appropriate command if configured differently

5. Rebuild Assets

After ensuring that all configurations and dependencies are correct and up to date, have him rebuild the assets:

    Recompile JavaScript: This can be done using:

    bash

    ./bin/webpack --watch  # Or another appropriate Webpack command as configured in your project

6. Check Environment Variables

    Environment Variables: Make sure that any necessary environment variables are set correctly in his development environment. This includes checking .env files or environment-specific settings that might influence how packages are loaded or built.

7. Try Running the Rails Server

After following these steps, he should try running the Rails server again and see if the JavaScript errors are resolved.
Summary

Following these steps should help ensure that your colleague's development environment is correctly set up and consistent with other environments, such as yours, where JavaScript is working as expected. If the problem persists even after taking these measures, it may be necessary to look deeper into any specific local environment issues or discrepancies in system configurations (like different OS versions, node versions, etc.).
```

**Review by hortongn — APPROVED** [review]
The problem is apparently the version of node on my computer.  I'm running v20.11.1 and staff-directory doesn't like that high of a version unless I
* `export NODE_OPTIONS=--openssl-legacy-provider`
* `bundle exec rails webpacker:install`
Then things work for me.  I think the earlier version of node on the servers is allowing it to work there.  So I'll merge this, but we'll need to make adjustments when we upgrade node on the servers.  Destroy works fine in this branch.

**Pull request merged**
